"""add model_confidence to wardrobe_items

Revision ID: 080ee2117f75
Revises: e895916a9142
Create Date: 2026-03-28 09:41:17.706628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '080ee2117f75'
down_revision = 'e895916a9142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wardrobe_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_confidence', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wardrobe_items', schema=None) as batch_op:
        batch_op.drop_column('model_confidence')

    # ### end Alembic commands ###
