"""add tryon_jobs and user profile_photo

Revision ID: 62cb9bb43a17
Revises: 85f8d2c21ee4
Create Date: 2026-03-30 14:14:59.823664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62cb9bb43a17'
down_revision = '85f8d2c21ee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tryon_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('person_photo_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result_filename', sa.String(length=256), nullable=True),
    sa.Column('error_msg', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['wardrobe_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tryon_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_tryon_cache_lookup', ['user_id', 'item_id', 'person_photo_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_tryon_jobs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_photo_filename', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_photo_filename')

    with op.batch_alter_table('tryon_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tryon_jobs_user_id'))
        batch_op.drop_index('ix_tryon_cache_lookup')

    op.drop_table('tryon_jobs')
    # ### end Alembic commands ###
