"""add outfit_plans table

Revision ID: 636f6522e1d2
Revises: 080ee2117f75
Create Date: 2026-03-28 16:47:05.254099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '636f6522e1d2'
down_revision = '080ee2117f75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outfit_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('occasion', sa.String(length=20), nullable=True),
    sa.Column('saved_outfit_id', sa.Integer(), nullable=True),
    sa.Column('item_ids', sa.Text(), nullable=True),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['saved_outfit_id'], ['saved_outfits.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'plan_date', name='uq_user_plan_date')
    )
    with op.batch_alter_table('outfit_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outfit_plans_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outfit_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outfit_plans_user_id'))

    op.drop_table('outfit_plans')
    # ### end Alembic commands ###
