"""add sub_category clip_confidence to wardrobe_items

Revision ID: 85f8d2c21ee4
Revises: 636f6522e1d2
Create Date: 2026-03-29 21:35:51.026304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f8d2c21ee4'
down_revision = '636f6522e1d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wardrobe_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_category', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('clip_confidence', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wardrobe_items', schema=None) as batch_op:
        batch_op.drop_column('clip_confidence')
        batch_op.drop_column('sub_category')

    # ### end Alembic commands ###
