"""add_social_remix_tables

Revision ID: d60cafc3551d
Revises: 62cb9bb43a17
Create Date: 2026-03-31 01:06:10.758794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd60cafc3551d'
down_revision = '62cb9bb43a17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vibe_tags',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('region', sa.Enum('global', 'south-asian'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('follower_id != following_id', name='chk_no_self_follow'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'following_id')
    )
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.create_index('idx_follows_follower', ['follower_id', 'created_at'], unique=False)
        batch_op.create_index('idx_follows_following', ['following_id', 'created_at'], unique=False)

    op.create_table('shared_outfits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('saved_outfit_id', sa.Integer(), nullable=False),
    sa.Column('caption', sa.String(length=300), nullable=True),
    sa.Column('preview_image_filename', sa.String(length=256), nullable=True),
    sa.Column('visibility', sa.Enum('public', 'followers', 'private'), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('remix_count', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('remix_source_post_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['remix_source_post_id'], ['shared_outfits.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['saved_outfit_id'], ['saved_outfits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shared_outfits', schema=None) as batch_op:
        batch_op.create_index('idx_so_feed', ['created_at', 'id'], unique=False)
        batch_op.create_index('idx_so_remix_src', ['remix_source_post_id'], unique=False)
        batch_op.create_index('idx_so_user', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_shared_outfits_user_id'), ['user_id'], unique=False)

    op.create_table('outfit_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shared_outfit_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shared_outfit_id'], ['shared_outfits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'shared_outfit_id', name='uq_outfit_like')
    )
    op.create_table('post_bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shared_outfit_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shared_outfit_id'], ['shared_outfits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'shared_outfit_id', name='uq_post_bookmark')
    )
    with op.batch_alter_table('post_bookmarks', schema=None) as batch_op:
        batch_op.create_index('idx_bookmarks_user', ['user_id', 'created_at'], unique=False)

    op.create_table('post_vibes',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('vibe_id', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['shared_outfits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vibe_id'], ['vibe_tags.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'vibe_id')
    )
    op.create_table('remix_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_shared_outfit_id', sa.Integer(), nullable=False),
    sa.Column('remixer_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['remixer_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_shared_outfit_id'], ['shared_outfits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('remix_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remix_logs_source_shared_outfit_id'), ['source_shared_outfit_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('follower_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('following_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('vibe_preferences', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fusion_mode_enabled', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_column('fusion_mode_enabled')
        batch_op.drop_column('vibe_preferences')
        batch_op.drop_column('is_public')
        batch_op.drop_column('following_count')
        batch_op.drop_column('follower_count')
        batch_op.drop_column('bio')
        batch_op.drop_column('username')

    with op.batch_alter_table('remix_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remix_logs_source_shared_outfit_id'))

    op.drop_table('remix_logs')
    op.drop_table('post_vibes')
    with op.batch_alter_table('post_bookmarks', schema=None) as batch_op:
        batch_op.drop_index('idx_bookmarks_user')

    op.drop_table('post_bookmarks')
    op.drop_table('outfit_likes')
    with op.batch_alter_table('shared_outfits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shared_outfits_user_id'))
        batch_op.drop_index('idx_so_user')
        batch_op.drop_index('idx_so_remix_src')
        batch_op.drop_index('idx_so_feed')

    op.drop_table('shared_outfits')
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_index('idx_follows_following')
        batch_op.drop_index('idx_follows_follower')

    op.drop_table('follows')
    op.drop_table('vibe_tags')
    # ### end Alembic commands ###
