"""add outfit history saved feedback tables

Revision ID: e895916a9142
Revises: 
Create Date: 2026-03-27 19:20:52.426863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e895916a9142'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('outfit_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('occasion', sa.String(length=20), nullable=False),
    sa.Column('temperature_used', sa.Float(), nullable=False),
    sa.Column('item_ids', sa.Text(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('template', sa.String(length=5), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outfit_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outfit_history_user_id'), ['user_id'], unique=False)

    op.create_table('saved_outfits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('occasion', sa.String(length=20), nullable=False),
    sa.Column('item_ids', sa.Text(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_saved_outfit_name_per_user')
    )
    with op.batch_alter_table('saved_outfits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_outfits_user_id'), ['user_id'], unique=False)

    op.create_table('wardrobe_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('formality', sa.String(length=10), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=False),
    sa.Column('color_hue', sa.Float(), nullable=False),
    sa.Column('color_sat', sa.Float(), nullable=False),
    sa.Column('color_val', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wardrobe_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wardrobe_items_user_id'), ['user_id'], unique=False)

    op.create_table('outfit_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['history_id'], ['outfit_history.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('history_id'),
    sa.UniqueConstraint('user_id', 'history_id', name='uq_feedback_per_user_history')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outfit_feedback')
    with op.batch_alter_table('wardrobe_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wardrobe_items_user_id'))

    op.drop_table('wardrobe_items')
    with op.batch_alter_table('saved_outfits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_outfits_user_id'))

    op.drop_table('saved_outfits')
    with op.batch_alter_table('outfit_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outfit_history_user_id'))

    op.drop_table('outfit_history')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
